### ISSUE TITLE
Invalid product version & build combination still gives 'valid' response

### ISSUE THREAD

**Issue by jorris** [release-engineering/product-listings-manager#46]
When given a mismatch between product version and a build that should be invalid, and thus 404, a response is nevertheless generated. The response maps from the variants of the product version to the build rpms, though they should not. This appears to be a problem in the original Brew composedb as well.

ex: RHEL-7 xorg-x11-server-1.17.4-17.el6

**Comment by hlin** [comment]
Both brew getProductListings API and PLM have this issue. It's because only package name is used when querying(a few packages use package version) but package release is never used. I'm not sure if it will cause other issue to use package release or is there a better way to check if given product and build are matchable.

**Comment by hlin** [comment]
I will close this issue because it could be avoid in users side(even though it's not the best solution). If you think it should be fixed, please file a new issue to Compose project in JIRA. Thanks for your understanding.
